cc_library(
  name='fea_extract_interface',
  srcs=[
    'fea_extract_interface.cc',
  ],
  deps=[
      '//feature_master/if:feature_master',
      '//common:fileutil',
      '//common:metric',
      '//common:util',
      '#unwind',
      '#dl',
      '#keyutils',
      '#resolv',
  ],
)

